name: byte_tracker
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  dio: ^5.8.0+1
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  very_good_analysis: ^7.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5

flutter:

  uses-material-design: true